# Generated by Django 6.0.3 on 2026-03-24 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientmessage'),
        ('projects', '0002_project_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmessage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_messages', to='projects.project'),
        ),
    ]
