# Generated by Django 6.0.3 on 2026-03-24 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_messagereply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmessage',
            name='response',
        ),
    ]
