# Generated by Django 6.0.3 on 2026-03-23 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('dev', 'Разработчик'), ('curator', 'Куратор'), ('analyst', 'Аналитик'), ('tester', 'Тестировщик'), ('accountant', 'Бухгалтер')], default='dev', max_length=20)),
                ('salary_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salary_formula', models.TextField(blank=True, help_text='JSON с условиями расчёта')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
