# Generated by Django 6.0.3 on 2026-03-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('dev', 'Разработчик'), ('curator', 'Куратор'), ('analyst', 'Аналитик'), ('tester', 'Тестировщик'), ('accountant', 'Бухгалтер'), ('admin', 'Администратор')], default='dev', max_length=20),
        ),
    ]
