# Generated by Django 6.0.3 on 2026-03-23 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('dev', 'Разработчик'), ('curator', 'Куратор'), ('analyst', 'Аналитик'), ('tester', 'Тестировщик'), ('accountant', 'Бухгалтер'), ('admin', 'Администратор'), ('client', 'Клиент')], default='dev', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary_formula',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.organization', verbose_name='Организация'),
        ),
    ]
