# Generated by Django 6.0.3 on 2026-03-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='invite_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код приглашения'),
        ),
    ]
