# Generated by Django 6.0.3 on 2026-03-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repository_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка на репозиторий'),
        ),
    ]
