name: Build – Проверка целостности проекта

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Установка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Установка зависимостей
      run: pip install -r requirements.txt
    - name: Проверка миграций
      run: python manage.py makemigrations --check --dry-run
    - name: Сбор статических файлов (проверка)
      run: python manage.py collectstatic --noinput --dry-run